### PR TITLE
Fix URLs and start migration to conda for build

### PR DESCRIPTION
**Pull request by lalalavi**
This pull request addresses issue [#697](https://github.com/HALFpipe/HALFpipe/issues/697 ). All of the python dependencies have been either found in conga-forge in another number for the version, or with another name. The only python package exception is `sqlalchemy` where for some reason pip continues to install it even though there is a recipe available in condaforge. 

The reason we want to migrate entirely to conda management is to simplify the `requirements.sh` file and the build of the `Dockerfile`. The next pull request will address the remaining packages, for which we expect to build a custom recipe for all.

### CODE REVIEW

**Review by HippocampusGirl — APPROVED** [review]
Awesome, thanks for catching this!

**Review by HippocampusGirl — CHANGES_REQUESTED** [review]
I think this pull request makes a bunch of changes, so it would be great to have a good description for why we are doing this.

**Comment by HippocampusGirl** [comment]
Also we can maybe remove line_profiler if it creates difficulties

**Comment by lalalavi** [comment]
Sounds good Lea! Just to be clear you want me to update the initial description of the URL right?

**Review by HippocampusGirl — APPROVED** [review]

**Pull request merged**
